### ISSUE TITLE
Updated CMakelist for  ABC

### ISSUE THREAD

**Issue by animeshbchowdhury** [krzhu/abcRL#2]
Hi Keren,

I want to use the pybind to use ABC API calls from python. As you mentioned, several macros needed to be defined in CMakelist from ABC's Makefile. Do you happen to have the CMakelist.txt which you used for your experiments? Currently, I have tried my best to define certain marcos from ABC's Makefile, but it is still throwing error.

Best,
Animesh

**Comment by krzhu** [comment]
No, I don't have it. And if I understand correctly, the flags are platform-dependent, such as setting the number of bits for certain data type.

This issue has a good solution and I think it is the correct way to go: https://github.com/krzhu/abc_py/issues/1
